FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractiv
# Avoid the download and installation of dependencies on rebuild; 
# but without harcoding them
RUN apt update && apt install -y sagemath && pip install pip-tools
RUN pip-compile pyproject.toml
RUN sage -python3 -m pip install -r requirements.txt
WORKDIR "/home/cryptographic_estimators/"
COPY . .
ENV SAGE_PKGS=/usr/share/sagemath/installed
RUN sage -python3 -m pip install --no-deps .
