name: Build documentation and deploy to gh-page
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Configure AWS Credential
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      #   with:
      #     registry-type: public

      - name: Pull API from BitBucket
        run: |
          cd ..|
          && git clone https://x-token-auth:${{ secrets.BITBUCKET_API_TOKEN }}@bitbucket.org/${{ secrets.BITBUCKET_ORG }}/${{ secrets.BITBUCKET_REPOSITORY }}.git |
          && cd ${{ secrets.BITBUCKET_REPOSITORY }} |
          && docker build -t estimators-api --file Dockerfile.local .

      # - name: Reset API task
      #   run: |
      #     aws ecs list-tasks --region me-central-1 --cluster estimators-cluster |
      #     python -c "import sys, json; print(json.load(sys.stdin)['taskArns'][0])" |
      #     xargs -I{} aws ecs stop-task --task {} --region me-central-1 --cluster estimators-cluster
