name: Generate and submit documentation
on:
  pull_request:
    types: [ closed ]
    branches:
      - feature/add-read-the-docs

jobs:
  generate-documentation:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'feature/add-read-the-docs'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build
      uses: docker/build-push-action@v4
      id: built-image
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        load: true
        tags: estimators-lib:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Generate documentation
      run: docker run --rm -v $PWD:/home/cryptographic_estimators/ cryptographic-estimators make doc

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.AUTHORIZATION_TOKEN }}
        message: "Update documentation"

    - name: Update develop branch
      uses: morbalint/git-merge-action@v1
      with:
        target: ${{ github.event.pull_request.base.ref }}
        source: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.AUTHORIZATION_TOKEN }}
        strategy_options: 'ours'
