name: Update changelog

on:
  push:
    branches:
      - 'fix/github-workflows'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: run-bash-file
        run: |
          git fetch 
          chmod 777 run_update_changelog.sh
          repository_name="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          should_add_last_changes_to_master=$(./run_update_changelog.sh $repository_name)
          echo "--> $should_add_last_changes_to_master"
          echo "should_add_last_changes_to_master=$should_add_last_changes_to_master" >> $GITHUB_ENV

      - name: commit-push-changes
        uses: actions-js/push@master
        if: ${{env.should_add_last_changes_to_master == 'true'}}
        with:
          github_token: ${{ secrets.AUTHORIZATION_TOKEN }}
          message: 'Changelog version updated'
          tags: true
          force: true
